name: Debug DockerHub Login

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DockerHub Credentials
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "::error::DOCKER_USERNAME is not set in repository secrets"
            exit 1
          fi
          if [ -z "${{ secrets.SPENDLESS_SECRET }}" ]; then
            echo "::error::SPENDLESS_TOKEN is not set in repository secrets"
            exit 1
          fi
          echo "Both DOCKER_USERNAME and SPENDLESS_SECRET secrets are set"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.SPENDLESS_SECRET }}

      # Rest of your workflow here
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spendless_banking_sim_backend:latest
