name: Continuous Integration and Deployment with Podman

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Podman and enable Docker compatibility
      run: |
        . /etc/os-release
        echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y install podman
        sudo ln -s /usr/bin/podman /usr/bin/docker  # Enable Docker compatibility

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Docker Image using Podman
      run: |
        docker build --arch amd64 -f ./Dockerfile -t spendless_banking_sim_backend ./
        docker tag localhost/spendless_banking_sim_backend:latest ${{ secrets.DOCKER_USERNAME }}/spendless_banking_sim_backend:latest

    - name: Docker Hub login using Environment Variables
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.SPENDLESS_TOKEN }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker Image using Podman (Docker Compatibility)
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spendless_banking_sim_backend:latest
