name: Continuous Integration and Deployment with Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker Image
      run: |
        docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/spendless-banking-sim:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/spendless-banking-sim:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/spendless-banking-sim:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spendless-banking-sim:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spendless-banking-sim:latest

    - name: Run tests (optional)
      run: |
        echo "Run tests here"

    - name: Deploy (if needed)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Add deployment commands here if necessary
        echo "Deploying......"
